//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargos
    {
        public int cgoCargoId { get; set; }
        public string cgoDescripcion { get; set; }
        public Nullable<int> tpcTipoCargoId { get; set; }
        public Nullable<bool> cgoEsConfidencial { get; set; }
        public Nullable<bool> cgoPersonalACargo { get; set; }
        public Nullable<bool> cgoAnulado { get; set; }
        public Nullable<int> nvlNivelId { get; set; }
    }
}
